version: "3.8"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mathduo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - db_data:/var/lib/postgresql/data

  server:
    build: ./server
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/mathduo
      PORT: 3000
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"

  web:
    build: ./web
    depends_on:
      - server
    ports:
      - "8080:80"

volumes:
  db_data:
